### ISSUE TITLE
How to uninstall cite2c

### ISSUE THREAD

**Issue by seechew** [takluyver/cite2c#22]
I wanted to uninstall cite2c in Jupyter. I did not find any documentation to do that.

**Comment by takluyver** [comment]
If you run `jupyter nbextension disable cite2c/main`, it won't be loaded. It will still be left on your system - we haven't really thought about a mechanism to uninstall nbextensions - but if it's not loaded, it should have no effect.

**Comment by kirk86** [comment]
This is important, now jupyter-lab has a context menu showing plugins and others you might want to discover similar to VSCode, but with the limitation that there's not way to easily uninstall plugins through a button similar to VSCode where you can install and uninstall plugins at will freely without any hassle.

Maybe this should be put for discussion with jupyter-lab community and maintainers?

**Comment by kirk86** [comment]
For instance in my case I had previously installed cite2c in a conda environment along with jupyter-lab.
Then completely removed that conda env and re-installed everything fresh, jupyter-lab, etc..., but without cite2c.
Now whenever I start jupyter-lab I keep getting the following errors, seems like some config files from cite2c still left on my system. 

Any idea how to remove those?

```
[W 2022-12-24 13:16:51.725 ServerApp] cite2c.handlers | error adding extension (enabled: True): The module 'cite2c.handlers' could not be found (No module named 'cite2c'). Are you sure the extension is installed?
    Traceback (most recent call last):
      File "/home/user/anaconda/envs/myenv/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 175, in _validate_name
        self._module, self._metadata = get_metadata(name)
      File "/home/user/anaconda/envs/myenv/lib/python3.10/site-packages/jupyter_server/extension/utils.py", line 55, in get_metadata
        module = importlib.import_module(package_name)
      File "/home/user/anaconda/envs/myenv/lib/python3.10/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
      File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
      File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'cite2c'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/user/anaconda/envs/myenv/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 320, in add_extension
        extpkg = ExtensionPackage(name=extension_name, enabled=enabled)
      File "/home/user/anaconda/envs/myenv/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 166, in __init__
        super().__init__(*args, **kwargs)
      File "/home/user/anaconda/envs/myenv/lib/python3.10/site-packages/traitlets/traitlets.py", line 1357, in __init__
        value = self._traits[key]._cross_validate(self, getattr(self, key))
      File "/home/user/anaconda/envs/myenv/lib/python3.10/site-packages/traitlets/traitlets.py", line 743, in _cross_validate
        value = obj._trait_validators[self.name](obj, proposal)
      File "/home/user/anaconda/envs/myenv/lib/python3.10/site-packages/traitlets/traitlets.py", line 1229, in __call__
        return self.func(*args, **kwargs)
      File "/home/user/anaconda/envs/myenv/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 177, in _validate_name
        raise ExtensionModuleNotFound(
    jupyter_server.extension.utils.ExtensionModuleNotFound: The module 'cite2c.handlers' could not be found (No module named 'cite2c'). Are you sure the extension is installed?
```
