### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by Oli4** [takluyver/cite2c#27]
I just cloned your project to my computer and tried to run python install.py. I got the following error message and if I start my notebooks with ipython notebook I do not see my folders and files anymore. Instead I see a folder called nbext and three files, \_\_init__.py, handlers.py and install.py

```
Installing nbextension ...
Enabling the nbextension ...
Enabling the server extension ...
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/notebook/serverextensions.py", line 111, in validate_serverextension
    mod = importlib.import_module(import_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 944, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'cite2c'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "install.py", line 26, in <module>
    main()
  File "install.py", line 22, in main
    enable_server_ext()
  File "install.py", line 17, in enable_server_ext
    toggle_serverextension_python('cite2c.handlers', enabled=True, user=True)
  File "/usr/local/lib/python3.5/dist-packages/notebook/serverextensions.py", line 84, in toggle_serverextension_python
    validate_serverextension(import_name, logger)
  File "/usr/local/lib/python3.5/dist-packages/notebook/serverextensions.py", line 114, in validate_serverextension
    logger.warning("Error loading server extension %s", import_name)
AttributeError: 'NoneType' object has no attribute 'warning'
```

**Comment by takluyver** [comment]
Sorry, I just changed the package structure and forgot to update the README. Try:

```
pip install cite2c
python -m cite2c.install
```

**Comment by Oli4** [comment]
This worked, thank you very much!

**Comment by takluyver** [comment]
Great :-)
