### ISSUE TITLE
Can't authenticate?

### ISSUE THREAD

**Issue by jona-sassenhagen** [takluyver/cite2c#38]
I've installed via pip. Opening a new notebook, I get the cite toolbar items. When I click it, a new tab opens at `http://localhost:8888/cite2c/zotero_oauth` and I get a popup `Opened a new tab to authenticate with Zotero. Once you have done this, please click OK.`. However, the new tab (`cite2c/zotero_oauth`) is a 404, and I can't see how I can authenticate anything. What am I doing wrong? Thanks!

**Comment by takluyver** [comment]
Have you started a new notebook server since you installed it? It adds a handler for `/cite2c/zotero_oauth`, but unfortunately the notebook server won't use the new handler until you restart it.

**Comment by jona-sassenhagen** [comment]
Thanks, that did it. I could make a PR to the README.md making this explicit?

**Comment by takluyver** [comment]
That would be good, thanks!

**Comment by espoirMur** [comment]
I am having the same issue, I installed the extension, restart the notebook but I am still getting this.

I am using a mac and the latest version of jupyter


if this can help here is the log I am getting after restarting my jupyter posterior to the extension installation

```
[W 11:42:05.894 NotebookApp] Error loading server extension cite2c.handlers
    Traceback (most recent call last):
      File "/Users/es.py/.pyenv/versions/3.6.5/lib/python3.6/site-packages/notebook/notebookapp.py", line 1670, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "/Users/es.py/.pyenv/versions/3.6.5/lib/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'cite2c'
[I 11:42:05.922 NotebookApp] [jupyter_nbextensions_configurator] enabled 0.4.1
[I 11:42:05.922 NotebookApp] Serving notebooks from local directory: /Users/es.py/Projects
[I 11:42:05.922 NotebookApp] The Jupyter Notebook is running at:
[I 11:42:05.922 NotebookApp] http://localhost:8888/?token=8aa090b02bfa689329df14a516e83818382c8f5c6c07ce88
[I 11:42:05.922 NotebookApp]  or http://127.0.0.1:8888/?token=8aa090b02bfa689329df14a516e83818382c8f5c6c07ce88
[I 11:42:05.922 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 11:42:05.932 NotebookApp]

    To access the notebook, open this file in a browser:
        file:///Users/es.py/Library/Jupyter/runtime/nbserver-1066-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=8aa090b02bfa689329df14a516e83818382c8f5c6c07ce88
     or http://127.0.0.1:8888/?token=8aa090b02bfa689329df14a516e83818382c8f5c6c07ce88
[W 11:42:28.116 NotebookApp] 404 GET /nbextensions/pydeck/extension.js?v=20210113114205 (::1) 10.31ms referer=http://localhost:8888/notebooks/Personal/balobi_nini/notebooks/2.Dynamic_Topic_Modeling.ipynb
[I 11:42:28.403 NotebookApp] Kernel started: 54489484-6fe2-43fb-afd1-2eb2cd6e49a5
[W 11:42:28.455 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20210113114205 (::1) 4.20ms referer=http://localhost:8888/notebooks/Personal/balobi_nini/notebooks/2.Dynamic_Topic_Modeling.ipynb
[W 11:42:31.364 NotebookApp] 404 GET /cite2c/zotero_oauth (::1) 1.77ms referer=http://localhost:8888/notebooks/Personal/balobi_nini/notebooks/2.Dynamic_Topic_Modeling.ipynb
[W 11:42:57.337 NotebookApp] 404 GET /cite2c/zotero_oauth (::1) 2.13ms referer=http://localhost:8888/notebooks/Personal/balobi_nini/notebooks/2.Dynamic_Topic_Modeling.ipynb
```

**Comment by takluyver** [comment]
The `No module named 'cite2c'` error looks like it's not installed correctly - Jupyter can't find the Python module.

It's been some years since I touched cite2c, though, so it's quite possible that even without that, changes in Zotero or in Jupyter may mean it no longer works.
